(val qsort 
   (mkclosure 
      (lambda ($closure xs) 
         (if (null? xs) 
            '() 
            (let* ([pivot (car xs)]
                   [rest (cdr xs)]
                   [right? (mkclosure 
                            (lambda ($closure n) 
                               (> n (CAPTURED-IN 0 $closure))) 
                            (cons pivot '()))]
                   [left? (o 
                            (mkclosure 
                               (lambda ($closure x) (not x)) 
                               '()) 
                            right?)]) 
              (append 
                 (qsort (filter left? rest)) 
                 (cons pivot (qsort (filter right? rest))))))) 
      '()))
(val iota^ 
   (mkclosure 
      (lambda ($closure n) (if (= n 0) '() (cons n (iota^ (- n 1))))) 
      '()))
(check-expect (qsort 
      (cons 
         65 
         (cons 
            15 
            (cons 
               87 
               (cons 
                  42 
                  (cons 
                     62 
                     (cons 
                        45 
                        (cons 
                           6 
                           (cons 
                              81 
                              (cons 
                                 53 
                                 (cons 
                                    34 
                                    (cons 
                                       33 
                                       (cons 
                                          82 
                                          (cons 
                                             79 
                                             (cons 
                                                7 
                                                (cons 
                                                   17 
                                                   (cons 
                                                      39 
                                                      (cons 
                                                         71 
                                                         (cons 
                                                            18 
                                                            (cons 
                                                               98 
                                                               (cons 
                                                                  92 
                                                                  (cons 
                                                                     77 
                                                                     (cons 
                                                                        41 
                                                                        (cons 
                                                                           51 
                                                                           (cons 
                                                                              16 
                                                                              (cons 
                                                                                 86 
                                                                                 (cons 
                                                                                    30 
                                                                                    (cons 
                                                                                       49 
                                                                                       (cons 
                                                                                          10 
                                                                                          (cons 
                                                                                             4 
                                                                                             (cons 
                                                                                                68 
                                                                                                (cons 
                                                                                                   35 
                                                                                                   (cons 
                                                                                                      52 
                                                                                                      (cons 
                                                                                                         69 
                                                                                                         (cons 
                                                                                                            12 
                                                                                                            (cons 
                                                                                                               85 
                                                                                                               (cons 
                                                                                                                  36 
                                                                                                                  (cons 
                                                                                                                     47 
                                                                                                                     (cons 
                                                                                                                        5 
                                                                                                                        (cons 
                                                                                                                           1 
                                                                                                                           (cons 
                                                                                                                              61 
                                                                                                                              (cons 
                                                                                                                                 74 
                                                                                                                                 (cons 
                                                                                                                                    64 
                                                                                                                                    (cons 
                                                                                                                                       31 
                                                                                                                                       (cons 
                                                                                                                                          80 
                                                                                                                                          (cons 
                                                                                                                                             25 
                                                                                                                                             (cons 
                                                                                                                                                29 
                                                                                                                                                (cons 
                                                                                                                                                   93 
                                                                                                                                                   (cons 
                                                                                                                                                      78 
                                                                                                                                                      (cons 
                                                                                                                                                         72 
                                                                                                                                                         (cons 
                                                                                                                                                            24 
                                                                                                                                                            (cons 
                                                                                                                                                               99 
                                                                                                                                                               (cons 
                                                                                                                                                                  48 
                                                                                                                                                                  (cons 
                                                                                                                                                                     76 
                                                                                                                                                                     (cons 
                                                                                                                                                                        19 
                                                                                                                                                                        (cons 
                                                                                                                                                                           66 
                                                                                                                                                                           (cons 
                                                                                                                                                                              70 
                                                                                                                                                                              (cons 
                                                                                                                                                                                 3 
                                                                                                                                                                                 (cons 
                                                                                                                                                                                    56 
                                                                                                                                                                                    (cons 
                                                                                                                                                                                       23 
                                                                                                                                                                                       (cons 
                                                                                                                                                                                          32 
                                                                                                                                                                                          (cons 
                                                                                                                                                                                             84 
                                                                                                                                                                                             (cons 
                                                                                                                                                                                                100 
                                                                                                                                                                                                (cons 
                                                                                                                                                                                                   91 
                                                                                                                                                                                                   (cons 
                                                                                                                                                                                                      58 
                                                                                                                                                                                                      (cons 
                                                                                                                                                                                                         20 
                                                                                                                                                                                                         (cons 
                                                                                                                                                                                                            60 
                                                                                                                                                                                                            (cons 
                                                                                                                                                                                                               26 
                                                                                                                                                                                                               (cons 
                                                                                                                                                                                                                  37 
                                                                                                                                                                                                                  (cons 
                                                                                                                                                                                                                     97 
                                                                                                                                                                                                                     (cons 
                                                                                                                                                                                                                        54 
                                                                                                                                                                                                                        (cons 
                                                                                                                                                                                                                           46 
                                                                                                                                                                                                                           (cons 
                                                                                                                                                                                                                              13 
                                                                                                                                                                                                                              (cons 
                                                                                                                                                                                                                                 21 
                                                                                                                                                                                                                                 (cons 
                                                                                                                                                                                                                                    63 
                                                                                                                                                                                                                                    (cons 
                                                                                                                                                                                                                                       28 
                                                                                                                                                                                                                                       (cons 
                                                                                                                                                                                                                                          14 
                                                                                                                                                                                                                                          (cons 
                                                                                                                                                                                                                                             59 
                                                                                                                                                                                                                                             (cons 
                                                                                                                                                                                                                                                67 
                                                                                                                                                                                                                                                (cons 
                                                                                                                                                                                                                                                   38 
                                                                                                                                                                                                                                                   (cons 
                                                                                                                                                                                                                                                      88 
                                                                                                                                                                                                                                                      (cons 
                                                                                                                                                                                                                                                         57 
                                                                                                                                                                                                                                                         (cons 
                                                                                                                                                                                                                                                            40 
                                                                                                                                                                                                                                                            (cons 
                                                                                                                                                                                                                                                               55 
                                                                                                                                                                                                                                                               (cons 
                                                                                                                                                                                                                                                                  94 
                                                                                                                                                                                                                                                                  (cons 
                                                                                                                                                                                                                                                                     11 
                                                                                                                                                                                                                                                                     (cons 
                                                                                                                                                                                                                                                                        95 
                                                                                                                                                                                                                                                                        (cons 
                                                                                                                                                                                                                                                                           22 
                                                                                                                                                                                                                                                                           (cons 
                                                                                                                                                                                                                                                                              44 
                                                                                                                                                                                                                                                                              (cons 
                                                                                                                                                                                                                                                                                 27 
                                                                                                                                                                                                                                                                                 (cons 
                                                                                                                                                                                                                                                                                    9 
                                                                                                                                                                                                                                                                                    (cons 
                                                                                                                                                                                                                                                                                       83 
                                                                                                                                                                                                                                                                                       (cons 
                                                                                                                                                                                                                                                                                          50 
                                                                                                                                                                                                                                                                                          (cons 
                                                                                                                                                                                                                                                                                             43 
                                                                                                                                                                                                                                                                                             (cons 
                                                                                                                                                                                                                                                                                                8 
                                                                                                                                                                                                                                                                                                (cons 
                                                                                                                                                                                                                                                                                                   90 
                                                                                                                                                                                                                                                                                                   (cons 
                                                                                                                                                                                                                                                                                                      73 
                                                                                                                                                                                                                                                                                                      (cons 
                                                                                                                                                                                                                                                                                                         75 
                                                                                                                                                                                                                                                                                                         (cons 
                                                                                                                                                                                                                                                                                                            96 
                                                                                                                                                                                                                                                                                                            (cons 
                                                                                                                                                                                                                                                                                                               89 
                                                                                                                                                                                                                                                                                                               (cons 
                                                                                                                                                                                                                                                                                                                  2 
                                                                                                                                                                                                                                                                                                                  '()))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))) 
   (reverse (iota^ 100)))
